version: '3.6'
services:
  portfolio-service:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile
      args:
        CONFIG_FILE: "portfolio-service-conf.json"
        GIT_COMMIT: $GIT_COMMIT
    depends_on:
      - nosql
  nosql:
    ulimits:
      nofile: 90000
    image: "aerospike:4.5.3.6"
    ports:
      - "2000:3000"
      - "2001:3001"
      - "2002:3002"
      - "2003:3003"
    logging:
      driver: "none"