version: '3.6' PortfolioS
services:
  portfolio-service:
    command: /bin/sh -c "export GIT_COMMIT=$$(git rev-parse HEAD)"
    build:
      context: ./..
      dockerfile: build/Dockerfile
      args:
        CONFIG_FILE: "deploy/model-service-conf.json"
        GIT_COMMIT: $GIT_COMMIT
    ports:
      - "80:8080"
  nosql:
    ulimits:
      nofile: 90000
    image: "aerospike:4.5.3.6"
    ports:
      - "100:3000"
      - "101:3001"
      - "102:3002"