name: Go
on:
  push:
    branches:
      - develop
      - master
      - release/*
jobs:

  build:
    name: GenerateSwaggerDoc
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download |
        go install github.com/swaggo/swag/cmd/swag

    - name: Generate
      run: /go/bin/swag init cmd/main.go -g cmd/main.go -d ./
    
    - name: Commit and merge swag docs
      uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: github.ref
        github_token: '${{ secrets.GITHUB_TOKEN  }}'
        github_pat: '${{ secrets.GITHUB_SWAGGER_COMMIT }}'
        source_folder: docs/
      if: success() && github.event == 'push'      
