name: GoLint
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Go-Linty
      uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_LINTY }}

