name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install your linters here
      - name: Set up Go 1.13
          uses: actions/setup-go@v1
          with:
            go-version: 1.13
          id: go

      - name: Get dependencies
        run: go install golang.org/x/lint/golint

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN_LINTY }}
          golint: true